name: EcobikeRental
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.3
  firebase_database: ^4.3.0
  firebase_core: ^0.5.2
  firebase_storage: ^5.2.0
  cached_network_image: ^2.4.1
  permission: ^0.1.7
  stop_watch_timer: ^0.6.0+1
  flutter_local_notifications: ^1.4.2
  google_nav_bar: ^2.0.0
  lint: ^1.0.0
  crypto: ^2.1.5
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
dev_dependencies:
  flutter_test:
    sdk: flutter
  google_maps_flutter: ^0.4.0
  geolocator: ^6.1.5
  line_icons: ^0.2.0
  bot_toast: ^3.0.5
  intl: ^0.16.1
  progress_dialog: ^1.1.0+1
  flutter_launcher_icons: ^0.8.0
flutter_icons:
  image_path: "images/iconApp.png"
  android: true
  ios: true
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
     - images/background2.png
     - images/facebook.png
     - images/google.png
     - images/title.png
     - images/backgroundDrawer.png
     - images/bikeParking.png
     - images/xedapdiendo.jpg
     - images/xedapdienden.jpg
     - images/xedapdienxanh.jpg
     - images/logobikemap.png
     - images/creditCardInfo.png
     - images/logout.gif
     - images/hello1.gif
     - images/iconApp.png
     - images/iconChip.png
     - images/cardInfo.png
     - images/logoCard.png
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
